export const copy = {
  app: {
    title: "Traceflow",
    subtitle: "在一个地方统一管理需求、场景、任务与验收。",
    primaryViewSwitchAriaLabel: "主视图切换",
  },
  views: {
    dashboard: "总览",
    workspace: "工作台",
  },
  workspace: {
    requirementsTitle: "需求列表",
    loadingRequirements: "正在加载需求列表...",
    loadingDetails: "正在加载详情...",
    emptySelection: "请选择一个需求，或先创建新需求。",
    requirementForm: {
      titleLabel: "需求标题",
      titlePlaceholder: "需求标题",
      summaryLabel: "需求摘要",
      summaryPlaceholder: "摘要",
      businessValueLabel: "业务价值",
      businessValuePlaceholder: "业务价值",
      acceptanceCriteriaLabel: "验收标准",
      acceptanceCriteriaPlaceholder: "验收标准",
      statusLabel: "需求状态",
      createButton: "创建需求",
    },
    requirementDetail: {
      editButton: "编辑",
      saveButton: "保存需求",
      cancelButton: "取消",
      editTitleLabel: "编辑需求标题",
      editSummaryLabel: "编辑需求摘要",
      editBusinessValueLabel: "编辑业务价值",
      editAcceptanceCriteriaLabel: "编辑验收标准",
      editStatusLabel: "编辑需求状态",
      businessValueLabel: "业务价值：",
      acceptanceCriteriaLabel: "验收标准：",
      noSummary: "暂无摘要。",
      notProvided: "未提供",
    },
    scenario: {
      title: "场景",
      featureNameLabel: "功能名称",
      featureNamePlaceholder: "功能名称",
      titleLabel: "场景标题",
      titlePlaceholder: "场景标题",
      givenLabel: "前提",
      givenPlaceholder: "前提",
      whenLabel: "当",
      whenPlaceholder: "当",
      thenLabel: "则",
      thenPlaceholder: "则",
      addButton: "添加场景",
      saveButton: "保存场景",
      cancelButton: "取消",
      editButton: "编辑",
      editFeatureLabel: (id: number) => `编辑场景功能 ${id}`,
      editTitleLabel: (id: number) => `编辑场景标题 ${id}`,
      editGivenLabel: (id: number) => `编辑场景前提 ${id}`,
      editWhenLabel: (id: number) => `编辑场景当 ${id}`,
      editThenLabel: (id: number) => `编辑场景则 ${id}`,
      editStatusLabel: (id: number) => `编辑场景状态 ${id}`,
    },
    task: {
      title: "任务",
      titleLabel: "任务标题",
      titlePlaceholder: "任务标题",
      descriptionLabel: "任务描述",
      descriptionPlaceholder: "描述",
      addButton: "添加任务",
      saveButton: "保存任务",
      cancelButton: "取消",
      unassigned: "未分配",
      editButton: "编辑",
      editTitleLabel: (id: number) => `编辑任务标题 ${id}`,
      editDescriptionLabel: (id: number) => `编辑任务描述 ${id}`,
      editOwnerLabel: (id: number) => `编辑任务负责人 ${id}`,
      editTypeLabel: (id: number) => `编辑任务类型 ${id}`,
      editStatusLabel: (id: number) => `编辑任务状态 ${id}`,
    },
    acceptance: {
      title: "验收记录",
      statusLabel: "验收状态",
      recordedByLabel: "记录人",
      recordedByPlaceholder: "记录人",
      notesLabel: "验收备注",
      notesPlaceholder: "备注",
      submitButton: "记录验收",
      unknown: "未知",
      noNotes: "暂无备注",
    },
    github: {
      title: "GitHub 链接",
      linkTypeLabel: "GitHub 链接类型",
      urlLabel: "GitHub URL",
      labelLabel: "GitHub 标签",
      labelPlaceholder: "标签",
      submitButton: "添加 GitHub 链接",
      noLabel: "无标签",
    },
    testSummary: {
      title: "测试摘要",
      sourceLabel: "测试摘要来源",
      sourcePlaceholder: "来源",
      resultLabel: "测试摘要结果",
      textLabel: "测试摘要内容",
      textPlaceholder: "摘要",
      reportUrlLabel: "测试摘要报告 URL",
      reportUrlPlaceholder: "报告链接",
      submitButton: "添加测试摘要",
      noSummary: "暂无摘要",
      noReportLink: "暂无报告链接",
    },
    draft: {
      loading: "生成中...",
      requirement: {
        title: "AI 需求草稿",
        rawInputLabel: "原始业务输入",
        rawInputPlaceholder: "原始业务输入",
        businessContextLabel: "业务背景",
        businessContextPlaceholder: "业务背景",
        designHintsLabel: "设计提示",
        designHintsPlaceholder: "设计提示",
        generateButton: "生成需求草稿",
        previewTitle: "草稿预览",
        draftTitleLabel: "草稿需求标题",
        draftSummaryLabel: "草稿需求摘要",
        draftBusinessValueLabel: "草稿业务价值",
        draftAcceptanceCriteriaLabel: "草稿验收标准",
        applyButton: "将草稿填入表单",
      },
      scenario: {
        generateButton: "生成场景草稿",
        featureNameLabel: "草稿功能名称",
        itemTitle: (index: number) => `草稿场景 ${index}`,
        removeButton: "移除",
        titleLabel: (index: number) => `草稿场景标题 ${index}`,
        givenLabel: (index: number) => `草稿场景前提 ${index}`,
        whenLabel: (index: number) => `草稿场景当 ${index}`,
        thenLabel: (index: number) => `草稿场景则 ${index}`,
        saveAllButton: "保存全部草稿场景",
      },
      task: {
        generateButton: "生成任务草稿",
        itemTitle: (index: number) => `草稿任务 ${index}`,
        removeButton: "移除",
        titleLabel: (index: number) => `草稿任务标题 ${index}`,
        descriptionLabel: (index: number) => `草稿任务描述 ${index}`,
        ownerLabel: (index: number) => `草稿任务负责人 ${index}`,
        typeLabel: (index: number) => `草稿任务类型 ${index}`,
        saveAllButton: "保存全部草稿任务",
      },
    },
  },
  dashboard: {
    title: "交付总览",
    subtitle: "以只读方式查看需求健康度与发布准备情况。",
    loadingTitle: "正在加载总览",
    loadingBody: "正在刷新汇总卡片和需求汇总数据。",
    errorTitle: "总览暂时不可用",
    errorBody: "当前无法加载交付总览，请稍后重试刷新。",
    retryLoad: "重新加载总览",
    cards: {
      totalRequirements: "需求总数",
      draft: "草稿",
      ready: "就绪",
      accepted: "已验收",
      atRisk: "有风险",
      needsDefinition: "待澄清",
      readyForReview: "待评审",
      missingScenarios: "缺少场景",
      missingTasks: "缺少任务",
    },
    activeFilterLabels: {
      status: "状态",
      acceptance: "验收",
      health: "健康度",
      traceability: "可追踪性",
    },
    activeFilterValues: {
      ready: "就绪",
      passed: "通过",
      failed: "失败",
      blocked: "阻塞",
      "needs-definition": "待澄清",
      "missing-scenarios": "缺少场景",
      "missing-tasks": "缺少任务",
      "at-risk": "有风险",
      accepted: "已验收",
      "in-progress": "进行中",
      "ready-for-review": "待评审",
      none: "暂无",
      draft: "草稿",
      done: "完成",
      in_progress: "进行中",
    },
    executiveSignals: {
      releaseReadinessTitle: "发布准备度",
      releaseReadinessSummary: "当前还没有已验收需求，发布信心仍依赖后续验收结果。",
      releaseReadinessSummaryWithCount: (count: number) => `已有 ${count} 个需求完成验收，可进入发布规划或演示准备。`,
      executionRiskTitle: "执行风险",
      executionRiskSummary: "当前没有需求因验收状态而被标记为风险项。",
      executionRiskSummaryWithCount: (count: number) => `当前有 ${count} 个需求处于风险状态，原因是验收失败或被阻塞。`,
      definitionGapsTitle: "定义缺口",
      definitionGapsSummary: "当前范围内的追踪覆盖情况良好。",
      definitionGapsSummaryWithCount: (missingScenarios: number, missingTasks: number) => `仍有 ${missingScenarios} 个场景缺口和 ${missingTasks} 个任务拆解缺口需要跟进。`,
    },
    executiveSummaryTitle: "管理摘要",
    executiveSummaryCaption: "面向管理与业务评审",
    metricGuideTitle: "指标说明",
    metricGuideCaption: "如何理解这个总览",
    metricGuideItems: {
      acceptedTitle: "已验收",
      acceptedBody: "最近一次验收已通过，说明该需求可进入发布或演示准备阶段。",
      atRiskTitle: "有风险",
      atRiskBody: "最近一次验收失败或被阻塞，交付信心下降，需要先完成后续处理。",
      missingTraceabilityTitle: "缺少场景 / 任务",
      missingTraceabilityBody: "需求定义仍不完整，需要业务或交付团队补充澄清后才能稳定推进。",
    },
    attentionNeededTitle: "待关注事项",
    attentionNeededCaption: "优先级最高的后续跟进行动",
    attentionNeededEmpty: "当前总览未发现需要立即处理的风险信号。",
    recommendedActionsTitle: "建议动作",
    recommendedActionsCaption: "业务和交付负责人下一步可以做什么",
    acceptedScopeTitle: "已验收范围快照",
    acceptedScopeCaption: "已经验证通过的需求",
    acceptedScopeEmpty: "当前还没有需求通过验收。",
    acceptedScopeRowSummary: (scenarioCount: number, taskCount: number, latestTestSummaryResult: string) => `${scenarioCount} 个场景，${taskCount} 个任务，最新测试摘要：${latestTestSummaryResult}。`,
    requirementSummaryTitle: "需求汇总",
    requirementSummaryCaption: "点击任意一行即可打开当前详情工作台。",
    filters: {
      activeFiltersAriaLabel: "当前总览筛选条件",
      statusAriaLabel: "总览状态筛选",
      acceptanceAriaLabel: "总览验收筛选",
      healthAriaLabel: "总览健康度筛选",
      traceabilityAriaLabel: "总览可追踪性筛选",
      clear: "清空筛选",
      allStatuses: "全部状态",
      allAcceptance: "全部验收状态",
      allHealth: "全部健康度",
      allTraceability: "全部可追踪性",
      inProgress: "进行中",
      atRisk: "有风险",
      needsDefinition: "待澄清",
      readyForReview: "待评审",
      noAcceptance: "暂无验收",
      missingScenarios: "缺少场景",
      missingTasks: "缺少任务",
    },
    table: {
      title: "标题",
      status: "状态",
      scenarios: "场景数",
      tasks: "任务数",
      acceptance: "验收",
      health: "健康度",
      testSummary: "测试摘要",
      updated: "更新时间",
    },
    emptyStateTitle: "暂无需求",
    emptyStateBody: "请先在工作台中创建第一个需求，以生成交付总览。",
    emptyFilteredBody: "没有需求符合当前筛选条件。请清空筛选以恢复完整列表。",
  },
} as const;

export type AppCopy = typeof copy;
